# Generated by Django 4.2.5 on 2023-11-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Antivirus'), (2, 'Microsoft_office'), (3, 'Windows')], verbose_name='Category'),
        ),
    ]
